const UM_MB_EM_BYTES = 1024 * 1024;

export const LIMITE_UPLOAD_ARQUIVO_MB = 500;
export const LIMITE_UPLOAD_ARQUIVO_BYTES =
  LIMITE_UPLOAD_ARQUIVO_MB * UM_MB_EM_BYTES;

export const FOLGA_MULTIPART_UPLOAD_MB = 10;
export const LIMITE_UPLOAD_REQUISICAO_BYTES =
  (LIMITE_UPLOAD_ARQUIVO_MB + FOLGA_MULTIPART_UPLOAD_MB) * UM_MB_EM_BYTES;

export const MENSAGEM_ARQUIVO_GRANDE =
  `Arquivo muito grande. Tamanho máximo: ${LIMITE_UPLOAD_ARQUIVO_MB}MB`;
